---
- hosts: local
  connection: local

  roles:
    ## Basics
    - {role: fish, tags: fish}
    - {role: git, tags: git}
    - {role: fonts, tags: fonts, when: "ansible_os_family == 'Darwin'"}
    - {role: home, tags: home}
    - {role: iterm, tags: iterm, when: "ansible_os_family == 'Darwin'"}
    - {role: tmux, tags: tmux}
    # - {role: vim, tags: vim}
    ## Basic development stuff
    # - {role: docker, tags: docker}
    - {role: editorconfig, tags: editorconfig, when: "ansible_os_family == 'Darwin'"}
    # - {role: jdk, tags: jdk}
    - {role: nodejs, tags: nodejs}
    # - {role: elm, tags: elm}
    # - {role: python3, tags: python3}
    # - {role: scala, tags: scala}
    # - {role: the-silver-searcher, tags: the-silver-searcher}
    # - {role: vagrant, tags: vagrant}
    # - {role: virtualbox, tags: virtualbox}
    - {role: vscode, tags: vscode, when: "ansible_os_family == 'Darwin'"}
    - {role: vscode-insiders, tags: vscode-insiders, when: "ansible_os_family == 'Darwin'"}
    # rbenv
    # google-cloud-sdk
    ## Mobile development stuff
    # - {role: android-ndk, tags: android-ndk}
    # - {role: android-sdk, tags: android-sdk}
    # - {role: watchman, tags: watchman}
    ## Applications
    # - {role: 1password, tags: 1password, when: "ansible_os_family == 'Darwin'"}
    # - {role: alfred, tags: alfred, when: "ansible_os_family == 'Darwin'"}
    # - {role: amethyst, tags: amethyst, when: "ansible_os_family == 'Darwin'"}
    # - {role: anki, tags: anki, when: "ansible_os_family == 'Darwin'"}
    # - {role: atom, tags: atom}
    # - {role: caffeine, tags: caffeine, when: "ansible_os_family == 'Darwin'"}
    # - {role: calibre, tags: calibre}
    # - {role: dash, tags: dash, when: "ansible_os_family == 'Darwin'"}
    # - {role: dropbox, tags: dropbox}
    # - {role: filezilla, tags: filezilla}
    # - {role: firefox, tags: firefox}
    # - {role: flux, tags: flux, when: "ansible_os_family == 'Darwin'"}
    # - {role: flycut, tags: flycut, when: "ansible_os_family == 'Darwin'"}
    # - {role: franz, tags: franz, when: "ansible_os_family == 'Darwin'"}
    # - {role: google-chrome, tags: google-chrome}
    # - {role: gpg, tags: gpg}
    # - {role: hipchat, tags: hipchat, when: "ansible_os_family == 'Darwin'"}
    - {role: karabiner-elements, tags: karabiner-elements, when: "ansible_os_family == 'Darwin'"}
    # - {role: keybase, tags: keybase}
    # - {role: jetbrains-toolbox, tags: jetbrains-toolbox}
    # - {role: little-snitch, tags: little-snitch, when: "ansible_os_family == 'Darwin'"}
    # - {role: rescuetime, tags: rescuetime, when: "ansible_os_family == 'Darwin'"}
    # - {role: seil, tags: seil, when: "ansible_os_family == 'Darwin'"}
    # - {role: sourcetree, tags: sourcetree, when: "ansible_os_family == 'Darwin'"}
    # - {role: spectacle, tags: spectacle, when: "ansible_os_family == 'Darwin'"}
    # - {role: tunnelblick, tags: tunnelblick, when: "ansible_os_family == 'Darwin'"}
    # - {role: unrarx, tags: unrarx, when: "ansible_os_family == 'Darwin'"}
    # - {role: usb-overdrive, tags: usb-overdrive, when: "ansible_os_family == 'Darwin'"}
    # - {role: vlc, tags: vlc}
    - {role: zoom, tags: zoom, when: "ansible_os_family == 'Darwin'"}