---
- name: Install nodejs (OS X)
  homebrew: name=node state=present
  when: ansible_os_family == 'Darwin'

- name: Install nodejs (Arch)
  pacman: name=nodejs state=present
  when: ansible_os_family == 'Archlinux'

- include_vars: darwin.yml
  when: ansible_os_family == 'Darwin'

- include_vars: arch.yml
  when: ansible_os_family == 'Archlinux'

- name: Write npmrc
  template: src=npmrc.j2 dest=~/.npmrc

- name: Install yarn (OS X)
  homebrew: name=yarn state=present
  when: ansible_os_family == 'Darwin'

- name: Install volta (OS X)
  homebrew: name=volta state=present
  when: ansible_os_family == 'Darwin'
