---
- name: Install Karabiner (OS X)
  homebrew_cask: name=karabiner-elements state=present

- name: Create Config dir
  file: path=~/.config/karabiner state=directory mode=0700

- name: Write Config
  copy: src=karabiner.json dest=~/.config/karabiner/karabiner.json
